FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_dummy
ARG SUPABASE_SERVICE_ROLE_KEY=sb_service_role_dummy
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=dummy-google-maps-key
ARG NEXT_PUBLIC_CRON_SECRET=dummy-cron-secret
ARG CRON_SECRET=dummy-cron-secret
ARG PLAID_ENV=sandbox
ARG PLAID_CLIENT_ID=dummy-plaid-client-id
ARG PLAID_SECRET=dummy-plaid-secret
ARG PLAID_TOKEN_ENCRYPTION_KEY=dummy-plaid-token-encryption-key
ARG VERCEL_URL=localhost:3000
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_CRON_SECRET=$NEXT_PUBLIC_CRON_SECRET
ENV CRON_SECRET=$CRON_SECRET
ENV PLAID_ENV=$PLAID_ENV
ENV PLAID_CLIENT_ID=$PLAID_CLIENT_ID
ENV PLAID_SECRET=$PLAID_SECRET
ENV PLAID_TOKEN_ENCRYPTION_KEY=$PLAID_TOKEN_ENCRYPTION_KEY
ENV VERCEL_URL=$VERCEL_URL
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ARG NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_dummy
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=dummy-google-maps-key
ARG NEXT_PUBLIC_CRON_SECRET=dummy-cron-secret
ARG VERCEL_URL=localhost:3000
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_CRON_SECRET=$NEXT_PUBLIC_CRON_SECRET
ENV VERCEL_URL=$VERCEL_URL

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
